FROM nemo-speech-runtime:latest

# Copy the model assets from the external modelcar image.
USER root
COPY --from=moosestack/nemotron-3.5-asr-streaming-0.6b-gguf_packaged-modelcar:latest /models /models

# OpenShift assigns a random UID with GID 0.
RUN chown -R 1001:0 /models && \
    chmod -R g+rwX /models

USER 1001
CMD ["--asr-model", "/models/nemotron-3.5-asr-streaming-0.6b.q8_0.gguf", "--host", "0.0.0.0", "--port", "8080"]
